const courseData = [
  {
    id: 1,
    name: 'Introduction to React Native',
    instructor: 'John Doe',
    description: 'Learn the basics of React Native development and build your first mobile app.',
    enrollmentStatus: 'Open',
    thumbnail: 'course1.png',
    duration: '8 weeks',
    schedule: 'Tuesdays and Thursdays, 6:00 PM - 8:00 PM',
    location: 'Online',
    prerequisites: ['Basic JavaScript knowledge', 'Familiarity with React'],
    syllabus: [
      { week: 1, topic: 'Introduction to React Native', content: 'Overview of React Native, setting up your development environment.' },
      { week: 2, topic: 'Building Your First App', content: 'Creating a simple mobile app using React Native components.' },
    ],
    students: [],
  },
  {
    id: 2,
    name: 'Advanced React Development',
    instructor: 'Jane Smith',
    description: 'Take your React skills to the next level with advanced topics and real-world projects.',
    enrollmentStatus: 'Open',
    thumbnail: 'course2.png',
    duration: '10 weeks',
    schedule: 'Mondays and Wednesdays, 7:00 PM - 9:00 PM',
    location: 'Online',
    prerequisites: ['Intermediate React knowledge', 'ES6 proficiency'],
    syllabus: [
      { week: 1, topic: 'Advanced State Management', content: 'Deep dive into state management in React applications.' },
      { week: 2, topic: 'Building a Single Page App', content: 'Creating a complex single-page application with routing.' },
    ],
    students: [],
  },
  {
    id: 3,
    name: 'Web Design Fundamentals',
    instructor: 'Alice Johnson',
    description: 'Learn the principles of web design and create visually appealing websites.',
    enrollmentStatus: 'Closed',
    thumbnail: 'course3.png',
    duration: '6 weeks',
    schedule: 'Saturdays, 10:00 AM - 12:00 PM',
    location: 'Online',
    prerequisites: ['None'],
    syllabus: [
      { week: 1, topic: 'Introduction to Web Design', content: 'Understanding the basics of web design principles.' },
      { week: 2, topic: 'Color Theory', content: 'Exploring color theory in web design.' },
    ],
    students: [],
  },
  {
    id: 4,
    name: 'Machine Learning Essentials',
    instructor: 'David Wilson',
    description: 'Get started with machine learning and build predictive models.',
    enrollmentStatus: 'Open',
    thumbnail: 'course4.png',
    duration: '12 weeks',
    schedule: 'Tuesdays and Thursdays, 7:00 PM - 9:00 PM',
    location: 'Online',
    prerequisites: ['Basic Python knowledge'],
    syllabus: [
      { week: 1, topic: 'Introduction to Machine Learning', content: 'Overview of machine learning concepts.' },
      { week: 2, topic: 'Supervised Learning', content: 'Understanding supervised learning algorithms.' },
    ],
    students: [],
  },
  {
    id: 5,
    name: 'Mobile App Development with Flutter',
    instructor: 'Emily Davis',
    description: 'Create cross-platform mobile apps using Flutter framework.',
    enrollmentStatus: 'In Progress',
    thumbnail: 'course5.png',
    duration: '9 weeks',
    schedule: 'Mondays and Wednesdays, 6:30 PM - 8:30 PM',
    location: 'Online',
    prerequisites: ['Basic programming knowledge'],
    syllabus: [
      { week: 1, topic: 'Introduction to Flutter', content: 'Getting started with Flutter and Dart programming.' },
      { week: 2, topic: 'Building User Interfaces', content: 'Designing user interfaces with Flutter widgets.' },
    ],
    students: [],
  },
  {
    id: 6,
    name: 'Data Science for Beginners',
    instructor: 'Sophia Adams',
    description: 'An introduction to data science and data analysis techniques.',
    enrollmentStatus: 'Open',
    thumbnail: 'course6.png',
    duration: '7 weeks',
    schedule: 'Fridays, 7:00 PM - 9:00 PM',
    location: 'Online',
    prerequisites: ['Basic statistics knowledge'],
    syllabus: [
      { week: 1, topic: 'Introduction to Data Science', content: 'Overview of data science and its applications.' },
      { week: 2, topic: 'Data Analysis Tools', content: 'Introduction to data analysis tools and libraries.' },
    ],
    students: [],
  },
  {
    id: 7,
    name: 'Full-Stack Web Development',
    instructor: 'Michael Brown',
    description: 'Learn to build modern web applications from front-end to back-end.',
    enrollmentStatus: 'Open',
    thumbnail: 'course7.png',
    duration: '14 weeks',
    schedule: 'Tuesdays and Thursdays, 6:00 PM - 8:00 PM',
    location: 'Online',
    prerequisites: ['Basic HTML, CSS, and JavaScript knowledge'],
    syllabus: [
      { week: 1, topic: 'Front-End Development', content: 'Creating interactive user interfaces with HTML, CSS, and JavaScript.' },
      { week: 2, topic: 'Back-End Development', content: 'Building server-side applications with Node.js and Express.' },
    ],
    students: [],
  },
  {
    id: 8,
    name: 'Artificial Intelligence Fundamentals',
    instructor: 'Olivia Clark',
    description: 'Explore the fundamentals of artificial intelligence and its applications.',
    enrollmentStatus: 'Open',
    thumbnail: 'course8.png',
    duration: '10 weeks',
    schedule: 'Wednesdays, 7:00 PM - 9:00 PM',
    location: 'Online',
    prerequisites: ['Basic programming knowledge'],
    syllabus: [
      { week: 1, topic: 'Introduction to AI', content: 'Overview of artificial intelligence concepts and history.' },
      { week: 2, topic: 'Machine Learning Algorithms', content: 'Exploring machine learning algorithms.' },
    ],
    students: [],
  },
  {
    id: 9,
    name: 'Digital Marketing Strategies',
    instructor: 'Ava Martinez',
    description: 'Learn effective digital marketing strategies to promote businesses online.',
    enrollmentStatus: 'Closed',
    thumbnail: 'course9.png',
    duration: '6 weeks',
    schedule: 'Saturdays, 10:00 AM - 12:00 PM',
    location: 'Online',
    prerequisites: ['None'],
    syllabus: [
      { week: 1, topic: 'Digital Marketing Fundamentals', content: 'Understanding the basics of digital marketing.' },
      { week: 2, topic: 'Social Media Marketing', content: 'Strategies for social media marketing.' },
    ],
    students: [],
  },
   
    {
      id: 10,
      name: 'Python Programming for Beginners',
      instructor: 'Liam Evans',
      description: 'A beginner-friendly course to learn Python programming from scratch.',
      enrollmentStatus: 'Open',
      thumbnail: 'course10.png',
      duration: '6 weeks',
      schedule: 'Mondays and Wednesdays, 6:30 PM - 8:30 PM',
      location: 'Online',
      prerequisites: ['None'],
      syllabus: [
        { week: 1, topic: 'Introduction to Python', content: 'Getting started with Python syntax and basics.' },
        { week: 2, topic: 'Control Flow and Functions', content: 'Understanding control structures and creating functions.' },
      ],
      students: [],
    },
    {
      id: 11,
      name: 'Front-End Web Development',
      instructor: 'Mia Turner',
      description: 'Master front-end web development with HTML, CSS, and JavaScript.',
      enrollmentStatus: 'Open',
      thumbnail: 'course11.png',
      duration: '12 weeks',
      schedule: 'Tuesdays and Thursdays, 6:00 PM - 8:00 PM',
      location: 'Online',
      prerequisites: ['Basic programming knowledge'],
      syllabus: [
        { week: 1, topic: 'HTML and CSS Fundamentals', content: 'Creating web pages with HTML and styling with CSS.' },
        { week: 2, topic: 'JavaScript Essentials', content: 'Introduction to JavaScript and DOM manipulation.' },
      ],
      students: [],
    },
    {
      id: 12,
      name: 'Data Visualization with D3.js',
      instructor: 'Ethan Green',
      description: 'Learn data visualization techniques using D3.js and create interactive charts.',
      enrollmentStatus: 'In Progress',
      thumbnail: 'course12.png',
      duration: '8 weeks',
      schedule: 'Mondays and Wednesdays, 7:00 PM - 9:00 PM',
      location: 'Online',
      prerequisites: ['Basic JavaScript knowledge'],
      syllabus: [
        { week: 1, topic: 'Introduction to Data Visualization', content: 'Overview of data visualization concepts.' },
        { week: 2, topic: 'D3.js Fundamentals', content: 'Getting started with D3.js library.' },
      ],
      students: [],
    },
    {
      id: 13,
      name: 'Android App Development with Kotlin',
      instructor: 'Noah Carter',
      description: 'Build Android apps using the Kotlin programming language.',
      enrollmentStatus: 'Open',
      thumbnail: 'course13.png',
      duration: '10 weeks',
      schedule: 'Saturdays, 9:00 AM - 11:00 AM',
      location: 'Online',
      prerequisites: ['Basic programming knowledge'],
      syllabus: [
        { week: 1, topic: 'Kotlin Fundamentals', content: 'Introduction to Kotlin and Android Studio.' },
        { week: 2, topic: 'Building User Interfaces', content: 'Designing Android app UIs.' },
      ],
      students: [],
    },
    {
      id: 14,
      name: 'Cybersecurity Fundamentals',
      instructor: 'Aiden White',
      description: 'Explore the basics of cybersecurity and learn to protect digital assets.',
      enrollmentStatus: 'Open',
      thumbnail: 'course14.png',
      duration: '8 weeks',
      schedule: 'Tuesdays and Thursdays, 7:00 PM - 9:00 PM',
      location: 'Online',
      prerequisites: ['Basic networking knowledge'],
      syllabus: [
        { week: 1, topic: 'Introduction to Cybersecurity', content: 'Overview of cybersecurity concepts.' },
        { week: 2, topic: 'Network Security', content: 'Securing computer networks and data.' },
      ],
      students: [],
    },
    {
      id: 15,
      name: 'iOS App Development with Swift',
      instructor: 'Ella Foster',
      description: 'Create iOS apps using the Swift programming language and Xcode.',
      enrollmentStatus: 'Closed',
      thumbnail: 'course15.png',
      duration: '12 weeks',
      schedule: 'Mondays and Wednesdays, 6:30 PM - 8:30 PM',
      location: 'Online',
      prerequisites: ['Basic programming knowledge'],
      syllabus: [
        { week: 1, topic: 'Swift Basics', content: 'Introduction to Swift and Xcode.' },
        { week: 2, topic: 'Building iOS Interfaces', content: 'Designing iOS app interfaces.' },
      ],
      students: [],
    },
    {
      id: 16,
      name: 'Blockchain Fundamentals',
      instructor: 'Lucas Miller',
      description: 'Learn the basics of blockchain technology and its applications.',
      enrollmentStatus: 'Open',
      thumbnail: 'course16.png',
      duration: '6 weeks',
      schedule: 'Fridays, 7:00 PM - 9:00 PM',
      location: 'Online',
      prerequisites: ['Basic cryptography knowledge'],
      syllabus: [
        { week: 1, topic: 'Introduction to Blockchain', content: 'Overview of blockchain technology and cryptocurrencies.' },
        { week: 2, topic: 'Blockchain Implementation', content: 'Building and deploying blockchain applications.' },
      ],
      students: [],
    },
    {
      id: 17,
      name: 'Graphic Design Essentials',
      instructor: 'Aria Turner',
      description: 'Learn graphic design principles and create stunning visual content.',
      enrollmentStatus: 'Open',
      thumbnail: 'course17.png',
      duration: '8 weeks',
      schedule: 'Thursdays, 6:00 PM - 8:00 PM',
      location: 'Online',
      prerequisites: ['Basic design software knowledge'],
      syllabus: [
        { week: 1, topic: 'Design Fundamentals', content: 'Understanding design principles and elements.' },
        { week: 2, topic: 'Adobe Photoshop Basics', content: 'Introduction to Photoshop for graphic design.' },
      ],
      students: [],
    },
    {
      id: 18,
      name: 'Digital Photography',
      instructor: 'Sophie Turner',
      description: 'Master the art of digital photography and capture stunning images.',
      enrollmentStatus: 'Open',
      thumbnail: 'course18.png',
      duration: '10 weeks',
      schedule: 'Saturdays, 9:00 AM - 11:00 AM',
      location: 'Online',
      prerequisites: ['Digital camera'],
      syllabus: [
        { week: 1, topic: 'Photography Basics', content: 'Introduction to camera settings and composition.' },
        { week: 2, topic: 'Photo Editing', content: 'Editing and enhancing digital photos.' },
      ],
      students: [],
    },
    {
      id: 19,
      name: 'UI/UX Design for Mobile Apps',
      instructor: 'Oliver Scott',
      description: 'Design user-friendly and visually appealing mobile app interfaces.',
      enrollmentStatus: 'Open',
      thumbnail: 'course19.png',
      duration: '12 weeks',
      schedule: 'Tuesdays and Thursdays, 6:30 PM - 8:30 PM',
      location: 'Online',
      prerequisites: ['Basic design principles'],
      syllabus: [
        { week: 1, topic: 'Mobile App Design Principles', content: 'Design guidelines and best practices for mobile apps.' },
        { week: 2, topic: 'Prototyping and User Testing', content: 'Creating prototypes and conducting user testing.' },
      ],
      students: [],
    },
    {
      id: 20,
      name: 'JavaScript Masterclass',
      instructor: 'Aiden Wilson',
      description: 'Become a JavaScript expert and develop complex web applications.',
      enrollmentStatus: 'Open',
      thumbnail: 'course20.png',
      duration: '14 weeks',
      schedule: 'Mondays and Wednesdays, 7:00 PM - 9:00 PM',
      location: 'Online',
      prerequisites: ['Intermediate JavaScript knowledge'],
      syllabus: [
        { week: 1, topic: 'Advanced JavaScript Concepts', content: 'Exploring advanced JavaScript features.' },
        { week: 2, topic: 'React.js Fundamentals', content: 'Introduction to React.js and building interactive web applications.' },
      ],
      students: [],
    },
  ];
  
  export default courseData;
  